### ISSUE TITLE
Button sends a request to the wrong webhook url

### ISSUE THREAD

**Issue by Taelkir** [ChristianLobaugh/sanity-plugin-dashboard-widget-amplify#2]
It looks like the button is hard-coded to https://webhooks.amplify.us-east-1.amazonaws.com/prod/webhooks?id=34b58cf5-f2d5-4dcb-af72-fcebae516e71&token=I1NRfbXU6uA9RbyQZK1QXkn0NryQn0Kzv90KchLMP38&operation=startbuild rather than paying attention to the provided webhookUrl prop.

**Comment by SimeonUnder2** [comment]
The version that `sanity install...` downloads still has this incorrect value

**Comment by ChristianLobaugh** [comment]
Yes - I never got around to meeting this change.

Thanks for reminding me.
